# Generated by Django 4.0.5 on 2022-06-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0002_plantmodel_image_alter_plantmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='PycharmProjects/Lab3-4/Images/', verbose_name='image'),
        ),
    ]
