# Generated by Django 4.0.5 on 2022-06-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0003_alter_plantmodel_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantmodel',
            name='image',
        ),
        migrations.AddField(
            model_name='plantmodel',
            name='cost',
            field=models.TextField(default=123, verbose_name='cost'),
            preserve_default=False,
        ),
    ]
