# Generated by Django 4.0.5 on 2022-06-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainform', '0004_remove_plantmodel_image_plantmodel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantmodel',
            name='img',
            field=models.ImageField(default='no_image.jpg', upload_to='product.image'),
        ),
    ]
